### ISSUE TITLE
Automatically generating test sets

### ISSUE THREAD

**Issue by mikeizbicki** [n8stringham/gensim-evaluations#2]
The next task is to automatically generate test sets for different languages based on wikidata.

Some ideas:
1. Use wikidata to translate existing test sets.
1. Use wikidata to automatically determine good categories and populate them for each language.

You will need to select several low resource languages to work with.

**Comment by n8stringham** [comment]
started working through SPARQL tutorial

**Comment by n8stringham** [comment]
Haven't updated in awhile...my bad. Been working on generating some good SPARQL queries and writing some code to turn those queries into a test set that works with our evaluation methods. Was able to get that code working today so now we can take a list of SPARQL queries and convert them into test sets for any language that we're interested in! 

Generating the SPARQL queries themselves "automatically" hasn't been as easy as we'd hoped, but this process has made the test set generation process easier and less arbitrary.
