### ISSUE TITLE
Method explanations

### ISSUE THREAD

**Issue by mikeizbicki** [n8stringham/gensim-evaluations#3]
I've added an explanation of the methods and runtimes to the `main.tex` file.  Make sure that you can get it to compile and that what I wrote matches what you actually did.

I realize there's not much working-day time before our next scheduled meeting, so it's okay if you can't get those tasks done before then, but it would be ideal if you could so we could talk about it.

**Comment by n8stringham** [comment]
Fixed the typos in `main.tex` that we talked about and started fixing the code implementation for the topk method.
