### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by n8stringham** [n8stringham/gensim-evaluations#7]
Hey Mike,
I've got a test version of the library for the low-resource evaluation methods uploaded to [test.pypi.org](https://test.pypi.org/project/lreval/0.0.5/) and I also updated the README of our repo to walkthrough some basic usage. 

I've got some questions for you before uploading the real thing. See you tomorrow

**Comment by n8stringham** [comment]
@mikeizbicki We talked about structuring the package so that it can be imported like
 `import gensim.evaluations`
But this causes problems since the user also needs to import other things from the official gensim package
for eg `import gensim.downloader as api` and
`from gensim.models import Word2Vec`

Is there a simple way to get around this issue or is it best to just change the names of the package structure?

**Comment by mikeizbicki** [comment]
This is the normal way to structure these extension packages, so it's definitely possible to do it in a way that doesn't cause problems.  But if you can't get it to work, it'd be okay for your version 0 to have it's own separate import namespaces.
